### ISSUE TITLE
سلام خسته نباشید 

### ISSUE THREAD

**Issue by Feriyali** [Ptechgithub/Brook#1]
داداش بی زحمت یه بررسی بکن اسکریپت موقع نصب به مشکل میخوره تو قسمت ssl و نمیتونه ssl بگیره

**Comment by Ptechgithub** [comment]
سلام چک کردم مشکلی نداره احتمالا چند بار پشت سر هم برای یک ساب دامین سرتیفیکیت گرفتید. یا سرور رو rebuild کنید یا ساب دامین رو عوض کنید
